name: Build Android APK

on:
  workflow_dispatch:
    inputs:
      release_type:
        description: 'Build type'
        required: true
        default: 'debug'
        type: choice
        options:
        - debug
        - release
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        
    - name: Setup Java JDK
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
        
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
      
    - name: Install Dependencies
      run: npm ci
      
    - name: Build Web App
      run: npm run build
      
    - name: Sync Capacitor
      run: npx cap sync android
      
    - name: Make Gradlew Executable
      run: chmod +x android/gradlew
      
    - name: Build Debug APK
      if: ${{ github.event.inputs.release_type == 'debug' || github.event.inputs.release_type == '' }}
      run: |
        cd android
        ./gradlew assembleDebug
        
    - name: Build Release APK
      if: ${{ github.event.inputs.release_type == 'release' }}
      run: |
        cd android
        ./gradlew assembleRelease
        
    - name: Upload Debug APK
      if: ${{ github.event.inputs.release_type == 'debug' || github.event.inputs.release_type == '' }}
      uses: actions/upload-artifact@v4
      with:
        name: infinite-wiki-debug.apk
        path: android/app/build/outputs/apk/debug/app-debug.apk
        
    - name: Upload Release APK
      if: ${{ github.event.inputs.release_type == 'release' }}
      uses: actions/upload-artifact@v4
      with:
        name: infinite-wiki-release.apk
        path: android/app/build/outputs/apk/release/app-release.apk
        
    - name: Create Release
      if: ${{ github.event.inputs.release_type == 'release' && github.ref == 'refs/heads/main' }}
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v${{ github.run_number }}
        release_name: Release v${{ github.run_number }}
        body: |
          Automatisch generierte APK-Datei für Infinite Wiki
          
          ## Änderungen
          - Neueste Version der Infinite Wiki App
          - Gemini API Integration
          - Offline-fähige APK
          
        draft: false
        prerelease: false